name: speedtest.net
on: workflow_dispatch
jobs:
  speedtest:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash && sudo apt-get install speedtest
